[tool.poetry]
name = "cells"
version = "0.1.0"
description = ""
authors = ["Ales Tsurko <ales.tsurko@gmail.com>"]

[tool.poetry.scripts]
cells = "cells.cells:main"

[tool.poetry.dependencies]
python = "^3.7"
rxpy = "^0.1.0"
pyside2 = "^5.13.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
